### PR TITLE
colorContrast function

### PR DESCRIPTION
**Pull request by Kerruba**
I've created the color contrast function. 
I've to say that's practically an adaptation of the code from Lea, but at least is a beginning.
I update the getLuminance method to adapt it to the relative luminance definition as stated [here](https://www.w3.org/TR/WCAG/#relativeluminancedef)

I'm sorry that I've updated also the format of the code

### CODE REVIEW

**Comment by brehaut** [comment]
Thanks for the pull request. I'm not going to merge it at this time. If you can fix up the stuff mentioned below that would be great.

I'm not happy with the format change of the code being in the same pull request as the actual behavior changes. It's really clouding what has changed. I presume this was done automatically by your editor.  I've no problem in fixing up the style (its pushing up against a decade old and reflects a time before good JS formatting support in editors). 

Two options here:  

- Don't change the formatting
- Change formatting in a separate pull request before this change. If you do so please keep the css named colors object on a single line. 

Regarding the changes themselves:

I haven't had a chance to look at the actual contrast function. A brief skim looks like its a direct port from Lea Verou's code; fine. We can address that more when its a clearer what the changes are (as above).

On the other hand, I'm not happy with the new implementation for `getLuminance`. 

- Ideally I want `getLuminance` to be consistent with the CSS color model's definition of luminance. If the old implemention does not then it needs to be changed. If it does, and the contrast ratio function needs a different implementation then it should be an inner function. 
- The comment still refers to the old implementation and the hyperlink to that. Is this still using the sample source algorithm? Please update this to reference the documentation about the new implementation, or add an additional reference about the scaling function (see next).
- The use of the for loop is weird and clouds the algorithm. Creating an array just for the purposes of iterating over part of it to then discard it is messy. I think this would be better served by a named inner function representing the body of the loop. Giving it a good name is vital. Without having the documentation for the reference algorithm on hand I don't have a strong feeling on what this should be, but off the top of my head `scaleComponent` would be a starting point. Simply apply this function to each component in the return expression. 

Finally, it appears there are no new test cases for luminance. It looks like the behavior is a fair bit more complex; I think the tests should reflect this.

Sorry that it appears to be a lot of changes, but thanks again for taking this on.

**Comment by Kerruba** [comment]
Thanks for your comments, I'll work out your requests as soon as possible :-)

**Comment by brehaut** [comment]
Not a problem; thanks for taking the time to work through this process

**Comment by Kerruba** [comment]
Hello, I'm actually working on a separate branch on this feature, using your suggestions. Still I was thinking, if you want, to split this into to different commits and pull requests. Indeed, looking at the WCAG reference documentation about [relative luminance](https://www.w3.org/TR/WCAG/#relativeluminancedef) and [contrast ratio](https://www.w3.org/TR/WCAG/#contrast-ratiodef), I can't find all the thigs Lea Verou did. So the first pull request will be exactly what the WCAG states, a future pull request will instead implement also Lea add-ons. Maybe together we can find the source of such implementation, or just believe that what she says is true

**Comment by brehaut** [comment]
That sounds good too me. Feel free to close this pull request and open a new one when you are ready. I've already merged your reformatting pull request seperately.

It might be that building the stuff Lea Verou's library does beyond the core WCAG stuff on top of the api exported by color-js might be the right choice (it seems like it makes a few assumptions about its use cases that are more specific to some domain than just manipulating colour)

**Pull request closed without merging**
